parameters:
    # URL alias router used for overriding URL alias view action
    netgen_ez_platform_site_api.urlalias_router.class: Netgen\Bundle\EzPlatformSiteApiBundle\Routing\UrlAliasRouter

    # Template defaults for standard eZ Platform installation
    # By default we don't override URL alias view action, for that reason these are commented out
    #ezplatform.default_view_templates.content.full: 'NetgenEzPlatformSiteApiBundle:default:content/full.html.twig'
    #ezsettings.default.pagelayout: 'NetgenEzPlatformSiteApiBundle::pagelayout.html.twig'

    # Defaults for semantic configuration
    netgen_ez_platform_site_api.default.override_url_alias_view_action: false
    netgen_ez_platform_site_api.default.url_alias_view_action: 'ng_content:viewAction'

services:
    netgen.ezplatform_site.core.find_service:
        class: Netgen\EzPlatformSite\Core\Site\FindService
        arguments:
            - '@netgen.ezplatform_site.core.domain_object_mapper'
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content'
            - '$languages$'
            - %netgen.ezplatform_site.use_always_available%

    netgen.ezplatform_site.core.load_service:
        class: Netgen\EzPlatformSite\Core\Site\LoadService
        arguments:
            - '@netgen.ezplatform_site.core.domain_object_mapper'
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.location'
            - '$languages$'
            - %netgen.ezplatform_site.use_always_available%

    netgen.ezplatform_site.view_builder.content:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Builder\ContentViewBuilder
        arguments:
            - '@netgen.ezplatform_site.site'
            - '@ezpublish.api.repository'
            - '@security.authorization_checker'
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'

    netgen.ezplatform_site.controller.content.view:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Content\ViewController
        parent: ezpublish.controller.base

    ng_content:
        alias: netgen.ezplatform_site.controller.content.view

    ezpublish.view_builder.registry:
        class: %ezpublish.view_builder.registry.class%
        calls:
            -
                - addToRegistry
                -
                    -
                        - '@ezpublish.view_builder.content'
                        - '@ezpublish.view_builder.block'
                        - '@netgen.ezplatform_site.view_builder.content'

    netgen.ezplatform_site.twig.extension.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingExtension
        arguments:
            - @ezpublish.templating.field_block_renderer
            - @ezpublish.fieldType.parameterProviderRegistry
        tags:
            - {name: twig.extension}
